import type { Metadata } from "next";
import {
  Hammersmith_One,
  Playfair_Display,
  Playfair_Display_SC,
  Poppins,
} from "next/font/google";

import "@/styles/globals.css";

import { cn } from "@/lib/utils";

import Providers from "./providers";

const metadata: Metadata = {
  title: "Sushimerksem",
  description: "Generated by create next app",
  icons: {
    icon: '/logo.png', // /public path
  },
};

export const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "600"],
  variable: "--font-poppins",
});

export const hammersmith = Hammersmith_One({
  subsets: ["latin"],
  display: "swap",
  weight: ["400"],
  variable: "--font-hammersmith-one",
});

export const playfair_Display_Sc = Playfair_Display_SC({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"],
  variable: "--font-playfair-display-sc",
});

export const playfair_Display = Playfair_Display({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "700"],
  variable: "--font-playfair-display",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
       <link rel="icon" href="/logo.png" sizes="any" />
      <body className={"relative"}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
